components:
  schemas:
    # Product Request Schemas
    CreateProductRequest:
      type: object
      required:
        - name
        - sku
        - category_id
        - base_price
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: "Product name"
          example: "Wireless Bluetooth Headphones"
        description:
          type: string
          maxLength: 2000
          description: "Product description"
          example: "High-quality wireless headphones with noise cancellation"
        sku:
          type: string
          minLength: 3
          maxLength: 100
          pattern: "^[A-Z0-9_-]+$"
          description: "Stock Keeping Unit - unique product identifier"
          example: "WBH-001"
        category_id:
          type: string
          format: uuid
          description: "Product category ID"
          example: "550e8400-e29b-41d4-a716-446655440001"
        brand:
          type: string
          maxLength: 100
          description: "Product brand"
          example: "AudioTech"
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 20
          description: "Product tags for categorization and search"
          example: ["electronics", "audio", "wireless"]
        base_price:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
          description: "Base price before any discounts"
          example: 199.99
        sale_price:
          type: number
          format: decimal
          minimum: 0
          description: "Sale price (if different from base price)"
          example: 149.99
        cost_price:
          type: number
          format: decimal
          minimum: 0
          description: "Cost price for profit calculations"
          example: 100.00
        stock_quantity:
          type: integer
          minimum: 0
          description: "Current stock quantity"
          example: 50
        low_stock_threshold:
          type: integer
          minimum: 0
          description: "Threshold for low stock alerts"
          example: 10
        track_inventory:
          type: boolean
          default: true
          description: "Whether to track inventory for this product"
          example: true
        weight:
          type: number
          format: decimal
          minimum: 0
          description: "Product weight in kg"
          example: 0.25
        dimensions_length:
          type: number
          format: decimal
          minimum: 0
          description: "Product length in cm"
          example: 20.0
        dimensions_width:
          type: number
          format: decimal
          minimum: 0
          description: "Product width in cm"
          example: 15.0
        dimensions_height:
          type: number
          format: decimal
          minimum: 0
          description: "Product height in cm"
          example: 8.0
        meta_title:
          type: string
          maxLength: 160
          description: "SEO meta title"
          example: "Premium Wireless Headphones - AudioTech"
        meta_description:
          type: string
          maxLength: 320
          description: "SEO meta description"
          example: "Experience premium sound quality with our wireless headphones"
        slug:
          type: string
          maxLength: 255
          pattern: "^[a-z0-9-]+$"
          description: "URL-friendly product slug"
          example: "wireless-bluetooth-headphones"
    
    UpdateProductRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: "Product name"
        description:
          type: string
          maxLength: 2000
          description: "Product description"
        sku:
          type: string
          minLength: 3
          maxLength: 100
          pattern: "^[A-Z0-9_-]+$"
          description: "Stock Keeping Unit - unique product identifier"
        category_id:
          type: string
          format: uuid
          description: "Product category ID"
        brand:
          type: string
          maxLength: 100
          description: "Product brand"
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 20
          description: "Product tags for categorization and search"
        base_price:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
          description: "Base price before any discounts"
        sale_price:
          type: number
          format: decimal
          minimum: 0
          description: "Sale price (if different from base price)"
        cost_price:
          type: number
          format: decimal
          minimum: 0
          description: "Cost price for profit calculations"
        stock_quantity:
          type: integer
          minimum: 0
          description: "Current stock quantity"
        low_stock_threshold:
          type: integer
          minimum: 0
          description: "Threshold for low stock alerts"
        track_inventory:
          type: boolean
          description: "Whether to track inventory for this product"
        status:
          type: string
          enum: [draft, active, inactive, archived]
          description: "Product status"
        weight:
          type: number
          format: decimal
          minimum: 0
          description: "Product weight in kg"
        dimensions_length:
          type: number
          format: decimal
          minimum: 0
          description: "Product length in cm"
        dimensions_width:
          type: number
          format: decimal
          minimum: 0
          description: "Product width in cm"
        dimensions_height:
          type: number
          format: decimal
          minimum: 0
          description: "Product height in cm"
        meta_title:
          type: string
          maxLength: 160
          description: "SEO meta title"
        meta_description:
          type: string
          maxLength: 320
          description: "SEO meta description"
        slug:
          type: string
          maxLength: 255
          pattern: "^[a-z0-9-]+$"
          description: "URL-friendly product slug"
    
    # Product Response Schemas
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "Unique product identifier"
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: "Product name"
          example: "Wireless Bluetooth Headphones"
        description:
          type: string
          description: "Product description"
          example: "High-quality wireless headphones with noise cancellation"
        sku:
          type: string
          description: "Stock Keeping Unit"
          example: "WBH-001"
        category_id:
          type: string
          format: uuid
          description: "Product category ID"
          example: "550e8400-e29b-41d4-a716-446655440001"
        brand:
          type: string
          description: "Product brand"
          example: "AudioTech"
        tags:
          type: array
          items:
            type: string
          description: "Product tags"
          example: ["electronics", "audio", "wireless"]
        base_price:
          type: number
          format: decimal
          description: "Base price before any discounts"
          example: 199.99
        sale_price:
          type: number
          format: decimal
          nullable: true
          description: "Sale price (if different from base price)"
          example: 149.99
        cost_price:
          type: number
          format: decimal
          nullable: true
          description: "Cost price for profit calculations"
          example: 100.00
        effective_price:
          type: number
          format: decimal
          description: "Final effective price (base_price or sale_price)"
          example: 149.99
        profit_margin:
          type: number
          format: decimal
          nullable: true
          description: "Calculated profit margin (effective_price - cost_price)"
          example: 49.99
        track_inventory:
          type: boolean
          description: "Whether inventory is tracked for this product"
          example: true
        stock_quantity:
          type: integer
          description: "Current stock quantity"
          example: 50
        low_stock_threshold:
          type: integer
          description: "Threshold for low stock alerts"
          example: 10
        is_low_stock:
          type: boolean
          description: "Whether the product is currently low in stock"
          example: false
        status:
          type: string
          enum: [draft, active, inactive, archived]
          description: "Product status"
          example: "active"
        weight:
          type: number
          format: decimal
          nullable: true
          description: "Product weight in kg"
          example: 0.25
        dimensions_length:
          type: number
          format: decimal
          nullable: true
          description: "Product length in cm"
          example: 20.0
        dimensions_width:
          type: number
          format: decimal
          nullable: true
          description: "Product width in cm"
          example: 15.0
        dimensions_height:
          type: number
          format: decimal
          nullable: true
          description: "Product height in cm"
          example: 8.0
        meta_title:
          type: string
          nullable: true
          description: "SEO meta title"
          example: "Premium Wireless Headphones - AudioTech"
        meta_description:
          type: string
          nullable: true
          description: "SEO meta description"
          example: "Experience premium sound quality with our wireless headphones"
        slug:
          type: string
          nullable: true
          description: "URL-friendly product slug"
          example: "wireless-bluetooth-headphones"
        created_by:
          type: string
          format: uuid
          description: "ID of user who created the product"
          example: "550e8400-e29b-41d4-a716-446655440002"
        created_at:
          type: string
          format: date-time
          description: "Product creation timestamp"
          example: "2025-09-24T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: "Product last update timestamp"
          example: "2025-09-24T10:00:00Z"
    
    ProductListItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "Unique product identifier"
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: "Product name"
          example: "Wireless Bluetooth Headphones"
        sku:
          type: string
          description: "Stock Keeping Unit"
          example: "WBH-001"
        brand:
          type: string
          nullable: true
          description: "Product brand"
          example: "AudioTech"
        base_price:
          type: number
          format: decimal
          description: "Base price"
          example: 199.99
        sale_price:
          type: number
          format: decimal
          nullable: true
          description: "Sale price"
          example: 149.99
        effective_price:
          type: number
          format: decimal
          description: "Final effective price"
          example: 149.99
        status:
          type: string
          enum: [draft, active, inactive, archived]
          description: "Product status"
          example: "active"
        stock_quantity:
          type: integer
          description: "Current stock quantity"
          example: 50
        is_low_stock:
          type: boolean
          description: "Whether the product is low in stock"
          example: false
        created_at:
          type: string
          format: date-time
          description: "Product creation timestamp"
          example: "2025-09-24T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: "Product last update timestamp"
          example: "2025-09-24T10:00:00Z"
    
    ProductListResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductListItem'
          description: "Array of products"
        pagination:
          $ref: '#/components/schemas/PaginationResponse'
          description: "Pagination metadata"
    
    PaginationResponse:
      type: object
      properties:
        page:
          type: integer
          description: "Current page number (1-based)"
          example: 1
        limit:
          type: integer
          description: "Number of items per page"
          example: 20
        total:
          type: integer
          description: "Total number of items"
          example: 42
        total_pages:
          type: integer
          description: "Total number of pages"
          example: 3
        has_next:
          type: boolean
          description: "Whether there is a next page"
          example: true
        has_prev:
          type: boolean
          description: "Whether there is a previous page"
          example: false
    
    # Common Response Schemas
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Operation completed successfully"
        data:
          description: "Response data (varies by endpoint)"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: "Error code for programmatic handling"
              example: "PRODUCT_NOT_FOUND"
            message:
              type: string
              description: "Technical error message"
              example: "Product not found"
            user_message:
              type: string
              description: "User-friendly error message"
              example: "The requested product could not be found."
            details:
              type: object
              description: "Additional error details (varies by error type)"
          required:
            - code
            - message
        request_id:
          type: string
          description: "Unique request identifier for debugging"
          example: "req_123456789"
        timestamp:
          type: string
          format: date-time
          description: "Error timestamp"
          example: "2025-09-24T10:00:00Z"
        path:
          type: string
          description: "Request path where error occurred"
          example: "/api/v1/products"
        method:
          type: string
          description: "HTTP method that caused the error"
          example: "POST"
      required:
        - error
        - request_id
        - timestamp
    
    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              enum: ["VALIDATION_FAILED"]
              description: "Validation error code"
              example: "VALIDATION_FAILED"
            message:
              type: string
              description: "General validation error message"
              example: "Request validation failed"
            fields:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: "Field name that failed validation"
                    example: "sku"
                  value:
                    description: "Value that failed validation"
                    example: "invalid-sku"
                  message:
                    type: string
                    description: "Specific validation error for this field"
                    example: "SKU must be 3-100 characters, uppercase alphanumeric with hyphens/underscores only"
                  rule:
                    type: string
                    description: "Validation rule that was violated"
                    example: "sku_format"
                required:
                  - field
                  - message
              description: "Array of field-specific validation errors"
          required:
            - code
            - message
            - fields
        request_id:
          type: string
          description: "Unique request identifier for debugging"
          example: "req_123456789"
        timestamp:
          type: string
          format: date-time
          description: "Error timestamp"
          example: "2025-09-24T10:00:00Z"
        path:
          type: string
          description: "Request path where error occurred"
          example: "/api/v1/products"
        method:
          type: string
          description: "HTTP method that caused the error"
          example: "POST"
      required:
        - error
        - request_id
        - timestamp